# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ByujiuELzpnNTmp_DQFOkNfLzIhbSP-4
"""

import pandas as pd


data = pd.read_csv('reviews.tsv', delimiter='\t')

data

#Lowercase -'Review' column
data['Review'] = data['Review'].str.lower()

data

import string

# Remove punctuation from the 'Review' column
translator = str.maketrans('', '', string.punctuation)
data['Review'] = data['Review'].apply(lambda x: x.translate(translator))

data

import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

# English stop words list
stop_words = set(stopwords.words('english'))
