# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ByujiuELzpnNTmp_DQFOkNfLzIhbSP-4
"""

import pandas as pd


data = pd.read_csv('reviews.tsv', delimiter='\t')

data

#Lowercase -'Review' column
data['Review'] = data['Review'].str.lower()

data

import string

# Remove punctuation from the 'Review' column
translator = str.maketrans('', '', string.punctuation)
data['Review'] = data['Review'].apply(lambda x: x.translate(translator))

data

import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

# English stop words list
stop_words = set(stopwords.words('english'))

# Remove stop words from the 'Review' column
data['Review'] = data['Review'].apply(lambda x: ' '.join([word for word in x.split() if word not in stop_words]))

data

import nltk
from nltk.stem import PorterStemmer

ps = PorterStemmer()

# Apply stemming to the 'Review' column
data['Stemmed_Review'] = data['Review'].apply(lambda x: ' '.join([ps.stem(word) for word in x.split()]))

data

from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

# Apply lemmatization to the 'Review' column
data['Lemmatized_Review'] = data['Review'].apply(lambda x: ' '.join([lemmatizer.lemmatize(word) for word in x.split()]))
data

