# -*- coding: utf-8 -*-
"""distlbert with lemm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rrgam5-7ofRbcBcXc3oOlDybE8_TnYu
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from transformers import DistilBertTokenizer, TFDistilBertForSequenceClassification
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.layers import Dropout
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

# Load the dataset
data = pd.read_csv('reviews.tsv', delimiter='\t')

# Text Preprocessing Functions
def preprocess_text(text):
    # Lowercase
    text = text.lower()

    # Remove punctuation
    translator = str.maketrans('', '', string.punctuation)
    text = text.translate(translator)

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    text = ' '.join([word for word in text.split() if word not in stop_words])

    # Stemming
    ps = PorterStemmer()
    text = ' '.join([ps.stem(word) for word in text.split()])

    # Lemmatization
    lemmatizer = WordNetLemmatizer()
    text = ' '.join([lemmatizer.lemmatize(word) for word in text.split()])

    return text

# Apply preprocessing to the dataset
nltk.download('stopwords')
nltk.download('wordnet')
data['Processed_Review'] = data['Review'].apply(preprocess_text)

# Split the dataset
train_data, val_test_data = train_test_split(data, test_size=0.3, random_state=42)
val_data, test_data = train_test_split(val_test_data, test_size=0.5, random_state=42)

# Initialize the tokenizer
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Function to encode the reviews
def encode_reviews(tokenizer, reviews, max_length=128):
    return tokenizer.batch_encode_plus(
        reviews,
        max_length=max_length,
        padding='max_length',
        truncation=True,
        return_tensors='tf'
    )

# Encode and prepare datasets
train_encodings = encode_reviews(tokenizer, train_data['Processed_Review'].tolist(), max_length=128)
val_encodings = encode_reviews(tokenizer, val_data['Processed_Review'].tolist(), max_length=128)
test_encodings = encode_reviews(tokenizer, test_data['Processed_Review'].tolist(), max_length=128)

# Convert to TensorFlow Datasets
train_dataset = tf.data.Dataset.from_tensor_slices((dict(train_encodings), train_data['Liked'].values)).shuffle(1000).batch(32)
val_dataset = tf.data.Dataset.from_tensor_slices((dict(val_encodings), val_data['Liked'].values)).batch(32)
test_dataset = tf.data.Dataset.from_tensor_slices((dict(test_encodings), test_data['Liked'].values)).batch(32)

# Define the custom DistilBERT model with dropout
class CustomDistilBertModel(tf.keras.Model):
    def __init__(self, model_name, num_classes, dropout_rate=0.2):
        super(CustomDistilBertModel, self).__init__()
        self.distilbert = TFDistilBertForSequenceClassification.from_pretrained(model_name, num_labels=num_classes)
        self.dropout = Dropout(dropout_rate)

    def call(self, inputs):
        distilbert_output = self.distilbert(inputs)
        output = self.dropout(distilbert_output.logits)
        return output

# Instantiate the custom model
model = CustomDistilBertModel('distilbert-base-uncased', num_classes=1, dropout_rate=0.2)

# Compile the model
optimizer = tf.keras.optimizers.Adam(learning_rate=2e-5)
loss = tf.keras.losses.BinaryCrossentropy(from_logits=True)
metric = tf.keras.metrics.BinaryAccuracy('accuracy')
model.compile(optimizer=optimizer, loss=loss, metrics=[metric])

# Callbacks for early stopping and learning rate reduction
early_stopping = EarlyStopping(monitor='val_loss', mode='min', patience=2, verbose=1)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=2, min_lr=1e-6, verbose=1)

# Train the model
model.fit(train_dataset, epochs=4, validation_data=val_dataset, callbacks=[early_stopping, reduce_lr])

# Evaluate the model
model.evaluate(test_dataset)

#THISSSS
import tensorflow as tf
