# -*- coding: utf-8 -*-
"""distlbert with lemm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rrgam5-7ofRbcBcXc3oOlDybE8_TnYu
"""

